"""05_file_path_unique

Revision ID: 157201d90dd2
Revises: 7c3124e2de18
Create Date: 2023-04-01 14:26:44.472229

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "157201d90dd2"
down_revision = "7c3124e2de18"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "file", ["path"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "file", type_="unique")
    # ### end Alembic commands ###
