"""03_file_id_as_uuid

Revision ID: 727be14c534a
Revises: d05f44eb0dba
Create Date: 2023-04-01 10:52:25.802548

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "727be14c534a"
down_revision = "d05f44eb0dba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
