"""04_file_id_uuid_default

Revision ID: 7c3124e2de18
Revises: 727be14c534a
Create Date: 2023-04-01 12:53:56.646158

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c3124e2de18"
down_revision = "727be14c534a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
