"""02_user_name_unique

Revision ID: d05f44eb0dba
Revises: 6ebc44589174
Create Date: 2023-03-31 22:10:12.231332

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d05f44eb0dba"
down_revision = "6ebc44589174"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    # ### end Alembic commands ###
